'From Pharo6.0 of 13 May 2016 [Latest update: #60499] on 21 November 2017 at 10:18:43.828472 pm'!!String methodsFor: '*10Pines-C17-2' stamp: 'HernanWilkinson 10/31/2016 23:57'!asPlural
	
	^self last = $s 
		ifTrue: [ self, 'es' ]
		ifFalse: [ self, 's' ]! !'From Pharo6.0 of 13 May 2016 [Latest update: #60499] on 21 November 2017 at 10:18:43.831528 pm'!!Object methodsFor: '*10Pines-C17-2' stamp: 'HernanWilkinson 10/31/2016 19:27'!toDo: aString 
	! !